dict_features = {
    'qc_first': "$E_{QC,1}$",
    'qc_second': "$E_{ARAP,1}$",
    'mips_first': "$E_{MIPS,1}$",
    'mips_second': "$E_{MIPS,2}$",
    'dirichlet_first': "$E_{Dirichlet,1}$",
    'dirichlet_second': "$E_{Dirichlet,2}$",
    'qi_first': "$E_{QI,1}$",
    'qi_second': "$E_{QI,2}$",
    'rigidity_first':  "$E_{QC,2}$",
    'rigidity_second': "$E_{ARAP,2}$",
    'symetric_first':  "$E_{AD,2}$",
    'symetric_second': "$E_{SD,2}$",
    'linear_first': "$E_{CF,1}$",
    'linear_second': "$E_{CF,2}$",
    'ad_list_first': "$E_{AD,1}$",
    'ad_list_second': "$E_{SD,1}$",

    "mean[0]": "$E_{MIPS,2}$",
    "mean[1]": "$E_{Dirichlet,1}$",
    "mean[2]": "$MFCC_{2}$" + " mean",
    "mean[3]": "$MFCC_{3}$" + " mean",
    "mean[4]": "$MFCC_{4}$" + " mean",
    "mean[5]": "$MFCC_{5}$" + " mean",
    "mean[6]": "$MFCC_{6}$" + " mean",
    "mean[7]": "$MFCC_{7}$" + " mean",
    "mean[8]": "$MFCC_{8}$" + " mean",
    "mean[9]": "$MFCC_{9}$" + " mean",
    "mean[10]": "$E_{Dirichlet,2}$",
    "mean[11]": "$E_{AD,2}$",

    "std[0]": "$MFCC_{0}$" + " std",
    "std[1]": "$MFCC_{1}$" + " std",
    "std[2]": "$MFCC_{2}$" + " std",
    "std[3]": "$MFCC_{3}$" + " std",
    "std[4]": "$MFCC_{4}$" + " std",
    "std[5]": "$MFCC_{5}$" + " std",
    "std[6]": "$MFCC_{6}$" + " std",
    "std[7]": "$MFCC_{7}$" + " std",
    "std[8]": "$MFCC_{8}$" + " std",
    "std[9]": "$MFCC_{9}$" + " std",
    "std[10]": "$MFCC_{10}$" + " std",
    "std[11]": "$MFCC_{11}$" + " std",

    "min_mfcc[0]": "$E_{MIPS,1}$",
    "min_mfcc[1]": "$E_{SD,2}$",
    "min_mfcc[2]": "$MFCC_{2}$" + " min",
    "min_mfcc[3]": "$MFCC_{3}$" + " min",
    "min_mfcc[4]": "$MFCC_{4}$" + " min",
    "min_mfcc[5]": "$MFCC_{5}$" + " min",
    "min_mfcc[6]": "$MFCC_{6}$" + " min",
    "min_mfcc[7]": "$MFCC_{7}$" + " min",
    "min_mfcc[8]": "$MFCC_{8}$" + " min",
    "min_mfcc[9]": "$MFCC_{9}$" + " min",
    "min_mfcc[10]": "$MFCC_{10}$" + " min",
    "min_mfcc[11]": "$MFCC_{11}$" + " min",

    "max_mfcc[0]": "$MFCC_{0}$" + "max",
    "max_mfcc[1]": "$MFCC_{1}$" + "max",
    "max_mfcc[2]": "$MFCC_{2}$" + "max",
    "max_mfcc[3]": "$MFCC_{3}$" + "max",
    "max_mfcc[4]": "$MFCC_{4}$" + "max",
    "max_mfcc[5]": "$MFCC_{5}$" + "max",
    "max_mfcc[6]": "$MFCC_{6}$" + "max",
    "max_mfcc[7]": "$MFCC_{7}$" + "max",
    "max_mfcc[8]": "$MFCC_{8}$" + "max",
    "max_mfcc[9]": "$MFCC_{9}$" + "max",
    "max_mfcc[10]": "$MFCC_{10}$" + "max",
    "max_mfcc[11]": "$MFCC_{11}$" + "max",

    "mean_diff[0]": "$MFCC_{0}$" + " $mean_{diff}$",
    "mean_diff[1]": "$MFCC_{1}$" + " $mean_{diff}$",
    "mean_diff[2]": "$MFCC_{2}$" + " $mean_{diff}$",
    "mean_diff[3]": "$MFCC_{3}$" + " $mean_{diff}$",
    "mean_diff[4]": "$MFCC_{4}$" + " $mean_{diff}$",
    "mean_diff[5]": "$MFCC_{5}$" + " $mean_{diff}$",
    "mean_diff[6]": "$MFCC_{6}$" + " $mean_{diff}$",
    "mean_diff[7]": "$MFCC_{7}$" + " $mean_{diff}$",
    "mean_diff[8]": "$MFCC_{8}$" + " $mean_{diff}$",
    "mean_diff[9]": "$MFCC_{9}$" + " $mean_{diff}$",
    "mean_diff[10]": "$MFCC_{10}$" + " $mean_{diff}$",
    "mean_diff[11]": "$E_{ARAP,1}$",

    "std_diff[0]": "$MFCC_{0}$" + " $std_{diff}$",
    "std_diff[1]": "$E_{QI,1}$",
    "std_diff[2]": "$MFCC_{2}$" + " $std_{diff}$",
    "std_diff[3]": "$MFCC_{3}$" + " $std_{diff}$",
    "std_diff[4]": "$MFCC_{4}$" + " $std_{diff}$",
    "std_diff[5]": "$E_{QI,1}$",
    "std_diff[6]": "$MFCC_{6}$" + " $std_{diff}$",
    "std_diff[7]": "$MFCC_{7}$" + " $std_{diff}$",
    "std_diff[8]": "$MFCC_{8}$" + " $std_{diff}$",
    "std_diff[9]": "$MFCC_{9}$" + " $std_{diff}$",
    "std_diff[10]": "$MFCC_{10}$" + " $std_{diff}$",
    "std_diff[11]": "$MFCC_{11}$" + " $std_{diff}$",

    'qc_noav': "$E_{QC,3}$",
    'mips_noav': "$E_{MIPS,3}$",
    'dirichlet_noav': "$E_{Dirichlet,3}$",
    'qi_noav': "$E_{QI,3}$",
    'rigidity_noav': "$E_{QC,3}$",
    'symetric_noav': "$E_{AD,3}$",
    'linear_noav': "$E_{CF,3}$",
    'ad_list_noav': "$E_{AD,3}$",
}